name: -- Deploy PRO

on:
  workflow_call:
    secrets:
      DOCKER_HUB_USERNAME:
        required: true
      DOCKER_HUB_ACCESS_TOKEN:
        required: true
      SSH_HOST:
        required: true
      SSH_USERNAME:
        required: true
      SSH_PASSWORD:
        required: true
      SSH_PORT:
        required: true
      NOTION_AUTH_TOKEN:
        required: true
      MAIN_DB_ID:
        required: true
      EXP_DB_ID:
        required: true
      PROJECT_DB_ID:
        required: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Run Docker container
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          password: ${{ secrets.SSH_PASSWORD }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            set -e
            
            # Ensure you're logged into Docker
            echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

            # Stop and remove existing container
            docker stop julianaranjo || true
            docker rm julianaranjo || true

            # Remove existing image
            docker rmi roigagusti/julianaranjo:latest || true

            # Run the new container
            docker run -d \
              --name julianaranjo \
              -p 8012:5000 \
              -e FLASK_APP=wsgi.py \
              -e FLASK_RUN_HOST=0.0.0.0 \
              -e NOTION_AUTH_TOKEN=${{ secrets.NOTION_AUTH_TOKEN }} \
              -e MAIN_DB_ID=${{ secrets.MAIN_DB_ID }} \
              -e EXP_DB_ID=${{ secrets.EXP_DB_ID }} \
              -e PROJECT_DB_ID=${{ secrets.PROJECT_DB_ID }} \
              roigagusti/julianaranjo:latest \
              poetry run flask run