name: Deploy to production

on:
  workflow_dispatch:

jobs:
  docker-build-and-push:
    uses: ./.github/workflows/_docker-build-and-push.yaml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

  deploy:
    needs: [ docker-build-and-push ]
    uses: ./.github/workflows/_deploy_pro.yaml
    secrets:
      DOCKER_HUB_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
      DOCKER_HUB_ACCESS_TOKEN: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_PORT: ${{ secrets.SSH_PORT }}
      NOTION_AUTH_TOKEN: ${{ secrets.NOTION_AUTH_TOKEN }}
      MAIN_DB_ID: ${{ secrets.MAIN_DB_ID }}
      TEACH_DB_ID: ${{ secrets.TEACH_DB_ID }}
      PROJECT_DB_ID: ${{ secrets.PROJECT_DB_ID }}